server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: JOYS1331

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: false